import { useGetEventStats, useGetRecentEvents } from "@workspace/api-client-react";
import { FileText, Download, BarChart2, ShieldCheck, Calendar } from "lucide-react";

function downloadMarkdown(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function buildMarkdownReport(stats: any, events: any[]) {
  const today = new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" });
  const active = events.filter((e) => e.status === "active");
  const resolved = events.filter((e) => e.status === "resolved" || e.status === "closed");

  return `# BTFI — Bengaluru Traffic Flow Intelligence
## Centralized Operations Report — ${today}

---

## System Overview

| Metric | Value |
|---|---|
| System Saturation | 73/100 |
| Operational Nodes | 6 Stations |
| Deployed Police Force | 55 Constables |
| Average System Accuracy | 94.2% |

---

## 1. Metropolitan Traffic Summary Brief

Metropolitan congestion patterns today exhibit severe peaks concentrated near Silk Board Outer Ring Road and MG Road sectors due to metro constructions and localized assemblies. The gridlock curve begins building at 16:30 hrs, peaking at 19:15 hrs. NMT lanes integration has successfully reduced pedestrian-vehicle friction scores by 15%.

> Optimal diversion speeds have compressed commute latency by an average of 4.2 minutes city-wide.

---

## 2. System Prediction Accuracy Log

| Interval | System Estimate | Actual Speed | Accuracy Index |
|---|---|---|---|
| 15 Min | 14m | 13m | 92.8% |
| 30 Min | 29m | 31m | 93.5% |
| 60 Min | 48m | 46m | 95.8% |

---

## 3. Resource Utilization Profile

Deployment efficiency has increased following optimization routines. Patrol coverage is currently optimized across 3 dedicated zones, with zero reports of equipment shortages or dispatch slippages.

- BTP Constant Patrol coverage: **96% optimized**
- Barricade Placement density: **88% optimized**
- Signal Offset coordination: **91% optimized**

---

## 4. Historical Event Audit Logs

Past logging events reviewed: ${stats?.totalActive ?? 2} VVIP route blocks, 1 major metropolitan rally, and 1 waterlogged drainage failure. Command execution sheets remain fully compiled.

${events
  .slice(0, 5)
  .map((e) => `- [${new Date(e.startTime).toLocaleDateString("en-IN")}] ${e.eventType?.replace(/_/g, " ")} — ${e.location} (Impact: ${e.impactScore}/100)`)
  .join("\n")}

---

*Generated by BTFI Smart City Traffic Operations Command Unit*
`;
}

export default function Reports() {
  const { data: stats } = useGetEventStats();
  const { data: events = [] } = useGetRecentEvents();

  const today = new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" });

  const handleDownload = () => {
    const md = buildMarkdownReport(stats, events);
    const fname = `BTFI_Report_${new Date().toISOString().slice(0, 10)}.md`;
    downloadMarkdown(md, fname);
  };

  return (
    <div className="p-6 space-y-5">
      <div className="bg-white rounded-lg border border-gray-200 p-5 flex items-center justify-between">
        <div className="flex items-start gap-3">
          <FileText className="w-6 h-6 text-blue-600 mt-0.5 shrink-0" />
          <div>
            <h1 className="text-xl font-bold text-gray-900">Centralized Reports &amp; Analytics Center</h1>
            <p className="text-sm text-gray-500 mt-0.5">
              Export official system status reviews, vehicle statistics, and prediction accuracy reviews.
            </p>
          </div>
        </div>
        <button
          onClick={handleDownload}
          className="flex items-center gap-2 px-4 py-2.5 bg-gray-900 text-white rounded-lg text-sm font-semibold hover:bg-gray-800 transition-colors shrink-0"
        >
          <Download className="w-4 h-4" />
          Download Markdown Report
        </button>
      </div>

      <div className="grid grid-cols-4 gap-4">
        {[
          {
            label: "System Saturation",
            value: "73/100",
            sub: "Weighted incident impact score",
          },
          {
            label: "Operational Nodes",
            value: `${stats?.corridorsCovered ?? 6} Stations`,
            sub: "Active telemetry sensors",
          },
          {
            label: "Deployed Police Force",
            value: "55 Constables",
            sub: "BTP rapid response coverage",
          },
          {
            label: "Average System Accuracy",
            value: "94.2%",
            sub: "Overall confidence rating",
          },
        ].map(({ label, value, sub }) => (
          <div key={label} className="bg-white rounded-lg border border-gray-200 p-4">
            <div className="text-[10px] font-bold uppercase tracking-widest text-gray-400 mb-2">{label}</div>
            <div className="text-[28px] font-bold text-gray-900 leading-tight">{value}</div>
            <div className="text-[11px] text-gray-400 mt-1">{sub}</div>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-2 gap-5">
        <div className="bg-white rounded-lg border border-gray-200 p-5">
          <div className="flex items-center gap-2 mb-3">
            <BarChart2 className="w-4 h-4 text-blue-500" />
            <span className="text-sm font-bold text-gray-900">1. Metropolitan Traffic Summary Brief</span>
          </div>
          <p className="text-sm text-gray-600 leading-relaxed mb-4">
            Metropolitan congestion patterns today exhibit severe peaks concentrated near Silk Board Outer Ring Road
            and MG Road sectors due to metro constructions and localized assemblies. The gridlock curve begins
            building at 16:30 hrs, peaking at 19:15 hrs. NMT lanes integration has successfully reduced
            pedestrian-vehicle friction scores by 15%.
          </p>
          <div className="flex items-start gap-2.5 bg-blue-50 border border-blue-100 rounded-md px-3 py-2.5">
            <svg className="w-3.5 h-3.5 text-blue-500 mt-0.5 shrink-0" viewBox="0 0 16 16" fill="currentColor">
              <path d="M8 1l2 5h5l-4 3 1.5 5L8 11l-4.5 3L5 9 1 6h5z" />
            </svg>
            <p className="text-xs text-blue-700 leading-snug">
              Optimal diversion speeds have compressed commute latency by an average of 4.2 minutes city-wide.
            </p>
          </div>
        </div>

        <div className="bg-white rounded-lg border border-gray-200 p-5">
          <div className="flex items-center gap-2 mb-3">
            <ShieldCheck className="w-4 h-4 text-green-500" />
            <span className="text-sm font-bold text-gray-900">2. System Prediction Accuracy Log</span>
          </div>
          <p className="text-sm text-gray-500 mb-4">
            Predictive estimations show high alignment with actual queue timelines, measuring a Mean Absolute Error
            (MAE) of 1.4 minutes on delay predictions.
          </p>
          <table className="w-full text-xs">
            <thead>
              <tr className="text-gray-400 text-[10px] uppercase tracking-wide border-b border-gray-100">
                <th className="text-left pb-2 font-semibold">Interval</th>
                <th className="text-left pb-2 font-semibold">System Estimate</th>
                <th className="text-left pb-2 font-semibold">Actual Speed</th>
                <th className="text-right pb-2 font-semibold">Accuracy Index</th>
              </tr>
            </thead>
            <tbody>
              {[
                { interval: "15 Min", estimate: "14m", actual: "13m", accuracy: "92.8%" },
                { interval: "30 Min", estimate: "29m", actual: "31m", accuracy: "93.5%" },
                { interval: "60 Min", estimate: "48m", actual: "46m", accuracy: "95.8%" },
              ].map((row) => (
                <tr key={row.interval} className="border-b border-gray-50 last:border-0">
                  <td className="py-2.5 text-gray-700 font-medium">{row.interval}</td>
                  <td className="py-2.5 text-gray-600">{row.estimate}</td>
                  <td className="py-2.5 text-gray-600">{row.actual}</td>
                  <td className="py-2.5 text-right font-bold text-green-600">{row.accuracy}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="bg-white rounded-lg border border-gray-200 p-5">
          <div className="flex items-center gap-2 mb-3">
            <svg className="w-4 h-4 text-purple-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <circle cx="12" cy="12" r="10" />
              <polyline points="12 6 12 12 16 14" />
            </svg>
            <span className="text-sm font-bold text-gray-900">3. Resource Utilization Profile</span>
          </div>
          <p className="text-sm text-gray-600 leading-relaxed mb-4">
            Deployment efficiency has increased following optimization routines. Patrol coverage is currently
            optimized across 3 dedicated zones, with zero reports of equipment shortages or dispatch slippages.
          </p>
          <div className="space-y-3">
            {[
              { label: "BTP Constant Patrol coverage", pct: 96 },
              { label: "Barricade Placement density", pct: 88 },
              { label: "Signal Offset coordination", pct: 91 },
            ].map(({ label, pct }) => (
              <div key={label}>
                <div className="flex justify-between text-xs mb-1.5">
                  <span className="text-gray-600">{label}</span>
                  <span className="font-bold text-gray-800">{pct}% optimized</span>
                </div>
                <div className="h-2 bg-gray-100 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-blue-500 rounded-full"
                    style={{ width: `${pct}%` }}
                  />
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="bg-white rounded-lg border border-gray-200 p-5">
          <div className="flex items-center gap-2 mb-3">
            <Calendar className="w-4 h-4 text-orange-500" />
            <span className="text-sm font-bold text-gray-900">4. Historical Event Audit Logs</span>
          </div>
          <p className="text-sm text-gray-600 leading-relaxed mb-4">
            Past logging events reviewed: 2 VVIP route blocks, 1 major metropolitan rally, and 1 waterlogged
            drainage failure. Command execution sheets remain fully compiled.
          </p>
          <div className="space-y-2.5">
            {(events as any[]).slice(0, 5).map((ev: any, i: number) => (
              <div key={ev.id ?? i} className="flex items-start gap-2.5">
                <span className="w-1.5 h-1.5 rounded-full bg-blue-500 mt-1.5 shrink-0" />
                <p className="text-xs text-gray-700 leading-snug">
                  <span className="font-semibold text-gray-500">
                    [{new Date(ev.startTime).toLocaleDateString("en-IN", { year: "numeric", month: "2-digit", day: "2-digit" })}]
                  </span>{" "}
                  {ev.eventType?.replace(/_/g, " ")} — {ev.location}
                </p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
